variables:
  IMAGE_REGISTRY: ${CI_IMAGE_REGISTRY}
  CONTAINER_CORE_IMAGE: ${CI_IMAGE_REGISTRY}/core:${CI_COMMIT_BRANCH}_${CI_COMMIT_SHORT_SHA}
  CONTAINER_SCHEDULER_IMAGE: ${CI_IMAGE_REGISTRY}/scheduler:${CI_COMMIT_BRANCH}_${CI_COMMIT_SHORT_SHA}

stages:
  - build
  - staging_environment
  - production_environment

build_core_image:
  stage: build
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $IMAGE_REGISTRY
    - docker pull $CONTAINER_CORE_IMAGE || true
    - docker build --cache-from=$CONTAINER_CORE_IMAGE -t $CONTAINER_CORE_IMAGE .
    - docker push $CONTAINER_CORE_IMAGE
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH == "dev"'
  tags:
    - mashup-runner

build_scheduler_image:
  stage: build
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $IMAGE_REGISTRY
    - docker pull $CONTAINER_SCHEDULER_IMAGE || true
    - docker build --cache-from=$CONTAINER_SCHEDULER_IMAGE -t $CONTAINER_SCHEDULER_IMAGE .
    - docker push $CONTAINER_SCHEDULER_IMAGE
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH == "dev"'
  tags:
    - mashup-runner
