# Build stage
FROM golang:1.24-alpine AS builder
WORKDIR /app

# Copy and download dependencies
COPY go.mod go.sum ./
RUN go mod download

# Copy the source code
COPY . .

# Build the application
RUN CGO_ENABLED=0 GOOS=linux go build -a -o scheduler-server ./cmd/scheduler

# Final stage
FROM alpine:3.18
WORKDIR /app

# Copy the binary from the builder stage
COPY --from=builder /app/scheduler-server .

# Run the binary
CMD ["./scheduler-server"]