# Build stage
FROM golang:1.24-alpine AS builder
WORKDIR /app

# Copy and download dependencies
COPY go.mod go.sum ./
RUN go mod download

# Copy the source code
COPY . .

# Build the application
RUN CGO_ENABLED=0 GOOS=linux go build -a -o core-server ./cmd/core

# Final stage
FROM alpine:3.18
WORKDIR /app

# Copy the binary from the builder stage
COPY --from=builder /app/core-server .

# Expose the port the API runs on
EXPOSE 8081

# Run the binary
CMD ["./core-server"]