-- -- Migration: Create Ticket_Group table
-- CREATE TABLE IF NOT EXISTS Ticket_Group (
--     ticket_group_id INT PRIMARY KEY AUTO_INCREMENT,
--     group_name VARCHAR(255) NOT NULL,
--     group_desc VARCHAR(255),
--     price_desc VARCHAR(255),
--     operatin_desc VARCHAR(255),
--     active_start_date DATETIME,
--     active_end_date CHAR(8),
--     group_type VARCHAR(255),
--     attachment_name VARCHAR(255),
--     attachment_path VARCHAR(255),
--     attachment_size BIGINT,
--     content_type VARCHAR(255),
--     unique_extension VARCHAR(255),
--     is_active BOOLEAN DEFAULT TRUE,
--     created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
--     updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
-- );