-- -- Migration: Create Banner table
-- CREATE TABLE IF NOT EXISTS Banner (
--     banner_id INT PRIMARY KEY AUTO_INCREMENT,
--     ticket_group_id INT NOT NULL,
--     placement INT,
--     redirect_url VARCHAR(255),
--     attachment_name VARCHAR(255),
--     attachment_path VARCHAR(255),
--     attachment_size BIGINT,
--     content_type VARCHAR(255),
--     unique_extension VARCHAR(255),
--     created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
--     updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
--     FOREIGN KEY (ticket_group_id) REFERENCES Ticket_Group(ticket_group_id)
-- );